-- Q-BU! schema (Auth + Telemetry)
-- Run this in Supabase SQL Editor.
--
-- NOTE:
-- - 行動ログは「未ログインでも」保存するため、Next.js API (/api/log) から
--   service role key を使って insert します。
-- - RLS は有効にして、クライアントからの直接 insert/select を基本的に塞ぎます。

-- 1) telemetry consents (anonymous)
create table if not exists public.telemetry_consents (
  anon_id uuid primary key,
  consented_at timestamptz not null default now(),
  consent_version text
);

alter table public.telemetry_consents enable row level security;

-- 2) event logs (anonymous + optional user)
create table if not exists public.event_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  anon_id uuid not null,
  user_id uuid references auth.users on delete set null,
  session_id uuid,
  event_name text not null,
  payload jsonb,
  path text,
  user_agent text,
  accept_language text,
  ip_hash text
);

create index if not exists event_logs_created_at_idx on public.event_logs (created_at desc);
create index if not exists event_logs_anon_id_idx on public.event_logs (anon_id);
create index if not exists event_logs_user_id_idx on public.event_logs (user_id);
create index if not exists event_logs_session_id_idx on public.event_logs (session_id);
create index if not exists event_logs_event_name_idx on public.event_logs (event_name);

alter table public.event_logs enable row level security;

-- Optional: allow logged-in user to read their own logs
-- NOTE: 本プロジェクトではクライアントから event_logs を読む想定がないため、
-- デフォルトでは SELECT ポリシーを作成しません。
-- 必要になったら、用途に合わせてポリシーを追加してください。

-- IMPORTANT:
-- We do NOT add an insert policy.
-- Insert is performed from the server using SUPABASE_SERVICE_ROLE_KEY.
